return function(bodyTagHandlers, env)
    require("tags.align")(bodyTagHandlers, env)
    require("tags.text")(bodyTagHandlers, env)
    require("tags.blit")(bodyTagHandlers, env)
    require("tags.big")(bodyTagHandlers, env)
    require("tags.br")(bodyTagHandlers, env)
    require("tags.color")(bodyTagHandlers, env)
    require("tags.img")(bodyTagHandlers, env)
    require("tags.script")(bodyTagHandlers, env)
    require("tags.hr")(bodyTagHandlers, env)
    require("tags.link")(bodyTagHandlers, env)
    --require("tags.window")
end